# Generated by Django 5.2.11 on 2026-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_slug_alter_restaurant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.ManyToManyField(blank=True, null=True, to='restaurants.cuisine'),
        ),
    ]
