# Generated by Django 5.2.11 on 2026-02-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user_ratings_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
