# Generated by Django 5.2.11 on 2026-03-01 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_user_ratings_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='dine_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='reservable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_beer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_breakfast',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_dinner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_lunch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_vegetarian_food',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_wine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='takeout',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wheelchair_accessible_entrance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('user', 'place_id')},
        ),
    ]
