# Generated by Django 5.2.11 on 2026-03-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_delivery_alter_restaurant_dine_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='source',
        ),
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
