# Generated by Django 5.2.11 on 2026-03-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_review_source_remove_review_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-active', '-created_at']},
        ),
    ]
