services:
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   env_file:
  #     - .env

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: rabbitmq-1
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   ports:
  #     - "5672:5672"  
  #     - "15672:15672" 
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
  #     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
  #   env_file:
  #     - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: worker-1
    command: celery --workdir src -A reviewaggregator worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - PYTHONPATH=/app/src
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: web-1
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./src:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}

volumes:
  media_volume:
  static_volume: