# Generated by Django 5.2.11 on 2026-02-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_init_email_customer_init_email_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_customer_id',
            new_name='stripe_id',
        ),
    ]
