# Generated by Django 5.2.11 on 2026-03-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('yelp', 'Yelp'), ('tripadvisor', 'TripAdvisor'), ('facebook', 'Facebook'), ('other', 'Other')], default='google', max_length=100),
        ),
    ]
