# Generated by Django 5.2.11 on 2026-03-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
