# Generated by Django 5.2.11 on 2026-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_rename_group_subscription_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['basic', 'advanced', 'pro'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
