# Generated by Django 5.2.11 on 2026-02-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscriptionprice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ('order', 'featured', '-updated_at')},
        ),
    ]
