# Generated by Django 5.2.11 on 2026-02-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscription_created_at_subscription_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ('subscription__order', 'order', 'featured', '-updated_at')},
        ),
    ]
