# Generated by Django 5.2.11 on 2026-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_usersubscription_cancel_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='previous_stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
