# Generated by Django 5.2.11 on 2026-02-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_aimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ai_models',
            field=models.ManyToManyField(blank=True, to='subscriptions.aimodel'),
        ),
    ]
