# Generated by Django 5.2.11 on 2026-02-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_subscription_ai_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_count_restaurant',
            field=models.IntegerField(default=0, help_text='Max number of restaurants that can be added userr with this subscription.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_count_review',
            field=models.IntegerField(default=0, help_text='Max number of reviews that can be scraped with this subscription.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='requst_to_celery',
            field=models.IntegerField(default=0, help_text='Number of requests that can be sent to celery day. 24=every hour, 1=every day, 0=dont sent.'),
        ),
    ]
