# Generated by Django 5.2.11 on 2026-03-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0024_subscription_max_count_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('free', 'Free permissions'), ('basic', 'Basic permissions'), ('advanced', 'Advanced permissions'), ('pro', 'Pro permissions')], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['free', 'basic', 'advanced', 'pro'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
