# Generated by Django 5.2.11 on 2026-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_count_active_restaurant',
            field=models.IntegerField(default=0, help_text='Max number of active restaurants that can be added userr with this subscription.'),
        ),
    ]
