name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku
        run: heroku container:login

      - name: Build and Push Web Image
        run: |
          docker build -f Dockerfile -t registry.heroku.com/$APP_NAME/web .
          docker push registry.heroku.com/$APP_NAME/web

      - name: Build and Push Worker Image
        run: |
          docker build -f Dockerfile.worker -t registry.heroku.com/$APP_NAME/worker .
          docker push registry.heroku.com/$APP_NAME/worker

      - name: Release Images
        run: heroku container:release web worker --app $APP_NAME

      - name: Run Migrations
        run: heroku run python src/manage.py migrate --app $APP_NAME

      - name: Collect Static Files
        run: heroku run "python src/manage.py collectstatic --noinput" --app $APP_NAME