name: Deploy to Heroku

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and Push Docker Image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Release Image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Build and Push Docker Worker Images
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:push web worker --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Release Images Worker
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web worker --app ${{ secrets.HEROKU_APP_NAME }}
      - name: Run Migrations

        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku run python src/manage.py migrate --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Collect Static Files
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku run "python src/manage.py collectstatic --noinput" --app ${{ secrets.HEROKU_APP_NAME }}